In [3]:
import torch
torch.__version__

'1.1.0.post2'

## Gradients

In [4]:
# A gradient tells you which direction
# you need to move when you aredoing ML -- positive or
# negative -- and well as having an actual numerical value
# that tells you 'how much' you should move

# a ML loop takes the gradients for a group
# of tensor operations, and then updates the value of the tensors
# that are being 'learned' using the product of the gradients
# and the learning rate

# But, 'a gradient with respect to what?' -- a loss function:
# you use gradients to figure the direction to go to make your loss smaller

In [6]:
# take the simplest algebra you can think of, e.g.:
#
# X + 1 = 3 
#
# and let's use a gradient to solve this simple stuff
# with simple ML.
#
# You start with a random initial guess

In [37]:
X = torch.rand(1, requires_grad=True)
X

tensor([0.0486], requires_grad=True)

In [38]:
# and the formula
Y = X + 1.0
Y

tensor([1.0486], grad_fn=<AddBackward0>)

In [39]:
# now, which is my loss? how far am I off from the result, i.e. 3?
# build a function that computes it:

In [40]:
def mse(Y):
    diff = 3.0 - Y
    return (diff ** 2).sum() / 2   # already prepared to deal with arrays, in this case a ingle floating point
loss = mse(Y)
print("-- Loss: ", loss)

-- Loss:  tensor(1.9040, grad_fn=<DivBackward0>)


In [41]:
# the gradient on our X -- that tells us which direction
# we are 'off' from the right answer -- let's look when we are too high

In [42]:
loss.backward() # here is the 'backpropagation' of the gradient
X.grad

tensor([-1.9514])

In [43]:
# we are ready to apply simple ML, i.e. a learning loop with a given learning rate:

In [46]:
learning_rate = 1e-3

for i in range(0, 10000):   # here is my learning loop
    #print("Learning in progress.. ", i, "/10000")
    Y = X + 1.0
    loss = mse(Y)   # compute the loss
    loss.backward()   # backpropagation
    # and here is the 'learning', so we turn off the graidents
    # from being updated temporarily
    with torch.no_grad():
        # the gradient tells you which direction you are off
        # so you go in the opposite direction to correct the problem
        X -= learning_rate * X.grad
        # and we zero out the gradients to get fresh values on 
        # each learning loop iteration
        X.grad.zero_()

In [47]:
# And the answer is:
X

tensor([1.9999], requires_grad=True)

In [48]:
# Of course this is approximate -- and that's an
# important point -- ML is going to approximate
# and you can control how close you get to the target answer
# by altering your learning rate or your number of iterations
#
# experiment with this by altering the `learning_rate`
# and the number of loops in `range`