In [2]:
import torch
torch.__version__

'1.1.0.post2'

## Tensors and basic tensor operations

In [ ]:
# lots of ways to create a tensor 
# https://pytorch.org/docs/stable/torch.html#creation-ops
# a tensor is really just a multidimensional array, starting
# with a simple empty array

In [3]:
e = torch.empty(2, 2)
e

tensor([[2.8958e+32, 1.4348e-19],
        [6.7211e+08, 1.1047e-32]])

In [ ]:
# ok - that's strange -- there are values in that array! this
# isn't a true random, it's just whatever was in memory -- if 
# you really want random, which is pretty often

In [4]:
r = torch.rand(2, 2)
r

tensor([[0.6550, 0.1798],
        [0.5096, 0.1883]])

In [5]:
# that's more like it and sometimes you just want specific values
# like a good old zero

In [6]:
z = torch.zeros(2, 2)
z

tensor([[0., 0.],
        [0., 0.]])

In [7]:
# or specifc constants, let's make some threes!

In [8]:
c = torch.full((2, 2), 3)
c 

tensor([[3., 3.],
        [3., 3.]])

In [ ]:
# the most flexible is the `torch.tensor` creation method, you can
# pass it data in a lot of formats -- starting with lists

In [9]:
l = torch.tensor([[1, 2], [3, 4]])
l

tensor([[1, 2],
        [3, 4]])

In [10]:
# as well as interoperate with numpy arrays, which is very
# handy to work with data you may have already processed
# with other machine learning tools liek sklearn

In [13]:
import numpy as np
n = np.linspace(0, 5, 5)
n

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [15]:
# turning this into pytorch is as easy as you would wish. Type changes from array (np) to a tensor.

In [14]:
nn = torch.tensor(n)
nn

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64)

In [16]:
# and back again is easy too!

In [17]:
nn.numpy()

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [18]:
# arrays support conventional operations -- like size..

In [19]:
nn.shape

torch.Size([5])

In [20]:
#.. and slice

In [23]:
nn[0]

tensor(0., dtype=torch.float64)

In [24]:
nn[1:]

tensor([1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64)

In [25]:
# in any creation method, you can also specify the data type
# like using a full precision floating point

In [26]:
s = torch.ones(3, 3, dtype=torch.float)
s

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
# all kinds of math operations are available
# https://pytorch.org/docs/stable/torch.html#math-operations
# math is straightforward operatos for common operations
# like:

In [36]:
# addition: add a bunch of zeroes to a 3x3 identity matrix

In [31]:
eye = torch.eye(3, 3) # identity matrix
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
eye + torch.zeros(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [37]:
# subtraction

In [38]:
eye - torch.ones(3, 3)

tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [39]:
# broadcast multiplication of a constant

In [40]:
eye * 3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [41]:
# broadcast division by a constant

In [42]:
eye / 3

tensor([[0.3333, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.3333]])

In [ ]:
# element wise tensor multiplication

In [43]:
eye * torch.full((3,3), 4)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [44]:
# and a (new!) dot product operator in python

In [45]:
x = torch.rand(3, 4)
y = torch.rand(4, 3)
x @ y

tensor([[1.3702, 0.8761, 1.3987],
        [1.1922, 0.8432, 1.6945],
        [1.5158, 1.0680, 2.0651]])

In [ ]:
# and handy machine learning component operations
# like getting the index of the maximum value

In [47]:
torch.tensor([1, 3, 356, 3, 0]).argmax()

tensor(2)