In [0]:
import torch
torch.__version__


'1.1.0'

## Advanced tensor operations

In [0]:
# You'll need a GPU to get this to run!

In [0]:
import torch


In [3]:
cpu = torch.device('cpu')
gpu = torch.device('cuda')
cpu

device(type='cpu')

In [4]:
cpu

device(type='cpu')

In [5]:
gpu

device(type='cuda')

In [0]:
# when you allocate a tensor, it's on a device, in the context
# of that device, if you don't specify, it's on the CPU

In [7]:
x = torch.tensor([1.5])
x, x.device

(tensor([1.5000]), device(type='cpu'))

In [0]:
# you can explicitly place it, which is how one does it in general. result is in this case just the same.

In [9]:
y = torch.tensor([2.5], device=cpu)
y, y.device

(tensor([2.5000]), device(type='cpu'))

In [0]:
# and now -- GPU
#
# NOTE: if you do not have access to a a GPU, the cell(s) below will give error
# (e.g. "AssertionError: Torch not compiled with CUDA enabled")
# if you have GPU, you should see e.g.:
# (tensor([3.5000], device='cuda:0'), device(type='cuda', index=0))

In [14]:
z = torch.tensor([3.5], device=gpu)
z, z.device

(tensor([3.5000], device='cuda:0'), device(type='cuda', index=0))

In [0]:
# you cannot mix devices, this is the important thing to remember
# particularly when loading up data -- make sure you put things
# together on a device!

In [25]:
print("x:", x, "on device:", x.device)
print("y:", y, "on device:", y.device)
print("z:", z, "on device:", z.device)
# this should give error:
a = x + y + z
a

x: tensor([1.5000]) on device: cpu
y: tensor([2.5000]) on device: cpu
z: tensor([3.5000], device='cuda:0') on device: cuda:0


RuntimeError: ignored

In [0]:
# but you can move things around to work on the gpu
# andf this should not give errors any more:

In [38]:
a = x.to(gpu) + y.to(gpu) + z
a

tensor([7.5000], device='cuda:0')

In [31]:
# more cleanly (and showing that one can move things back to the CPU, too):
a, a.device


(tensor([7.5000]), device(type='cpu'))

In [32]:
b = a.to(cpu)
b, b.device

(tensor([7.5000]), device(type='cpu'))

In [41]:
print("x:", x, "on device:", x.device)
print("y:", y, "on device:", y.device)
print("z:", z, "on device:", z.device)
#
print("\nAssign new vars and use GPU:\n")
x_gpu = x.to(gpu)
y_gpu = y.to(gpu)
print("x_gpu:", x, "on device:", x_gpu.device)
print("y_gpu:", y, "on device:", y_gpu.device)
#
print("\nRun operation here\n")
#
#a = x.to(gpu) + y.to(gpu) + z
a = x_gpu + y_gpu + z
#
print("a:", a, "on device:", a.device)
#
print("\nBring the result (a) back to CPU\n")
a_cpu = a.to(cpu)
print("a_cpu:", y, "on device:", a_cpu.device)

x: tensor([1.5000]) on device: cpu
y: tensor([2.5000]) on device: cpu
z: tensor([3.5000], device='cuda:0') on device: cuda:0

Assign new vars and use GPU:

x_gpu: tensor([1.5000]) on device: cuda:0
y_gpu: tensor([2.5000]) on device: cuda:0

Run operation here

a: tensor([7.5000], device='cuda:0') on device: cuda:0

Bring the result (a) back to CPU

a_cpu: tensor([2.5000]) on device: cpu
